// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixnyudauectgctcuwvih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bnl1ZGF1ZWN0Z2N0Y3V3dmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwNTkyNDQsImV4cCI6MjA0NjYzNTI0NH0.O52YEWEykDOaezAE7Rkm44HhesD7w8eUDtMMi82xve0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);